$ErrorActionPreference='Stop'
$root='C:\Users\gjpat\.codex\visualizations\2026\07\25\019f9725-e843-78c3-840c-539c3894ce28';$logo='C:\hotels-in-alibaug\guest-checkin\logo.webp';$mp4=Join-Path $root 'checkin-police-big-text-detailed-contact.mp4';$pptx=Join-Path $root 'checkin-police-big-text-detailed-contact.pptx'
$slides=@(
@('CHECKIN','Police Access Module','CHECKIN proposes one role-focused workspace for authorised police enquiries involving participating hotels. It brings relevant guest and hotel records into a clear workflow while retaining the context of each review.'),
@('ONE WORKSPACE','Search across hotels','An officer can search across participating hotels by guest name, mobile number or vehicle number. This supports faster initial verification without relying on fragmented registers, calls or informal messages.'),
@('CURRENT VISIBILITY','Current Guests','For a time-sensitive enquiry, this report provides a focused view of people presently staying at the selected hotel. It is designed for fast review on a mobile or desktop screen.'),
@('HISTORICAL RECORDS','Guest Register','The register presents check-in and check-out information for a selected date range. Officers can narrow records by guest, mobile, room, vehicle or ID reference and export the reviewed result for official follow-up.'),
@('PROPERTY CONTEXT','Hotel & Staff Details','Hotel Details provides the property identity, contact information and high-level occupancy context before a guest record is reviewed. The Staff Register can also support a recorded staff verification.'),
@('ACCOUNTABILITY','Access Logs','Each authorised report request can be retained as a reviewable access-log entry. This creates an audit trail that supports transparent data governance and disciplined handling of sensitive records.'),
@('PROPOSED OUTCOME','A responsible pilot for Alibaug','The requested outcome is approval to demonstrate and pilot this controlled Police Access Module with Alibaug hotels, supporting lawful enquiries through faster coordination, clearer information and accountable access.'),
@('CONTACT','Girish Jagnnath Patil','Hotels In Alibaug\n9769766678  •  72089 93889\ncheckin.hotelsinalibaug@gmail.com')
)
function rgb($c,$r,$g,$b){$c.RGB=$r+($g*256)+($b*65536)}
$app=New-Object -ComObject PowerPoint.Application;$app.Visible=-1;$deck=$null
try{$deck=$app.Presentations.Add();$deck.PageSetup.SlideWidth=1920;$deck.PageSetup.SlideHeight=1080;for($i=0;$i -lt $slides.Count;$i++){$s=$deck.Slides.Add($deck.Slides.Count+1,12);$s.FollowMasterBackground=$false;rgb $s.Background.Fill.ForeColor 6 25 54;$accent=$s.Shapes.AddShape(1,0,0,36,1080);$accent.Line.Visible=$false;rgb $accent.Fill.ForeColor 33 181 194;$pic=$s.Shapes.AddPicture($logo,$false,$true,1630,60,180,80);$pic.Line.Visible=$false;$tag=$s.Shapes.AddTextbox(1,120,110,1200,48);$tag.TextFrame.TextRange.Text=$slides[$i][0];$tag.TextFrame.TextRange.Font.Size=22;$tag.TextFrame.TextRange.Font.Bold=$true;rgb $tag.TextFrame.TextRange.Font.Color 95 218 228;$tag.Line.Visible=$false;$tag.Fill.Visible=$false;$title=$s.Shapes.AddTextbox(1,120,260,1550,210);$title.TextFrame.TextRange.Text=$slides[$i][1];$title.TextFrame.TextRange.Font.Name='Aptos Display';$title.TextFrame.TextRange.Font.Size=62;$title.TextFrame.TextRange.Font.Bold=$true;rgb $title.TextFrame.TextRange.Font.Color 255 255 255;$title.Line.Visible=$false;$title.Fill.Visible=$false;$body=$s.Shapes.AddTextbox(1,124,570,1450,280);$body.TextFrame.TextRange.Text=$slides[$i][2];$body.TextFrame.TextRange.Font.Name='Aptos';$body.TextFrame.TextRange.Font.Size=26;rgb $body.TextFrame.TextRange.Font.Color 205 226 239;$body.Line.Visible=$false;$body.Fill.Visible=$false;$num=$s.Shapes.AddTextbox(1,120,960,500,32);$num.TextFrame.TextRange.Text=('0{0} / 08' -f ($i+1));$num.TextFrame.TextRange.Font.Size=16;rgb $num.TextFrame.TextRange.Font.Color 125 153 182;$num.Line.Visible=$false;$num.Fill.Visible=$false;$s.SlideShowTransition.EntryEffect=3849;$s.SlideShowTransition.AdvanceOnTime=$true;$s.SlideShowTransition.AdvanceTime=8};if(Test-Path $pptx){Remove-Item $pptx -Force};if(Test-Path $mp4){Remove-Item $mp4 -Force};$deck.SaveAs($pptx);$deck.CreateVideo($mp4,$false,5,1920,30,85);Start-Sleep 20;$deadline=(Get-Date).AddMinutes(8);while(((Test-Path $mp4)-eq $false -or (Get-Item $mp4).Length -lt 1MB) -and (Get-Date)-lt $deadline){Start-Sleep 10};Get-Item $mp4|Select-Object FullName,Length}catch{throw}finally{if($deck){try{$deck.Close()}catch{}};$app.Quit()}
