$ErrorActionPreference='Stop'
$root='C:\Users\gjpat\.codex\visualizations\2026\07\25\019f9725-e843-78c3-840c-539c3894ce28';$source=Join-Path $root 'checkin-police-12-slide-launch-v2.pptx';$audioDir=Join-Path $root 'police-12-slide-english-audio';$out=Join-Path $root 'checkin-police-12-slide-launch-narrated-v2.mp4';$pptx=Join-Path $root 'checkin-police-12-slide-launch-narrated-v2.pptx'
$lines=@(
'Welcome to Checkin Police Access Module. This proposal is designed for responsible coordination between authorised police officers and participating hotels in Alibaug. The aim is simple: during a legitimate enquiry, relevant information should be easier to locate, review and account for, while the hospitality experience remains welcoming for every guest.',
'Alibaug is welcoming more families, visitors and tourism activity every day. Hotels need clear records, but they also need to keep their focus on service. Checkin helps participating hotels organise essential guest information in a structured digital workflow, so responsible record keeping supports hospitality instead of interrupting it.',
'The Police Dashboard is the starting point for an authorised officer. It provides a focused entry to the Police Reports area, keeping police-specific functions separate from hotel and superadmin operations. This role-based approach helps ensure that each user sees the tools relevant to their responsibility.',
'From the Police Reports home, an officer can choose the exact type of review required. The workspace connects all-hotels search, hotel details, current guests, the guest register, staff register and access logs. It is designed to avoid unnecessary navigation and to keep the next operational step clear.',
'All Hotels Guest Search helps with the first stage of a broader enquiry. An authorised officer can search participating hotels using a guest name, mobile number or vehicle number. This can reduce time spent contacting several properties individually and helps identify the relevant hotel record more quickly.',
'Current Guests provides a focused view of people presently staying at the selected hotel. During a time-sensitive enquiry, this can support faster situational awareness. The report is designed to work on both mobile and desktop screens, keeping information centred on the selected property.',
'For enquiries about an earlier period, the Guest Register provides check-in and check-out records for a selected date range. The officer can narrow results by guest, mobile number, room, vehicle or identification reference. The reviewed result can then be exported as a CSV file for an official follow-up process.',
'Hotel Details gives important context before an officer reviews an enquiry. It presents the property identity, available contact details and a high-level occupancy snapshot. This supports confirmation that the correct hotel has been selected and gives a clear operational picture of the property.',
'The Staff Register supports a staff-related verification when required. It provides recorded team information, including role, contact details and active status. Keeping this information in the same Police Reports workspace helps officers move from guest context to hotel context without searching through separate systems.',
'Accountability is essential whenever sensitive information is reviewed. The Access Logs section retains a reviewable history of police report activity. This audit trail can support transparent data governance for police, participating hotels and the service provider, and encourages disciplined use of the access module.',
'The Police Access Module is not intended to replace established police procedure. It is a controlled digital support tool for lawful enquiries. By bringing authorised search, relevant records and an access trail into one workflow, it can help make coordination faster, clearer and more accountable.',
'We respectfully request approval to demonstrate and pilot this Police Access Module with participating hotels in Alibaug. Thank you for considering a practical approach to safer hospitality coordination. For a demonstration or further discussion, please contact Girish Jagnnath Patil at the details shown on screen.'
)
Add-Type -AssemblyName System.Speech;New-Item -ItemType Directory -Path $audioDir -Force|Out-Null;$timings=@();for($i=0;$i -lt $lines.Count;$i++){$f=Join-Path $audioDir ('slide-{0:00}.wav' -f ($i+1));$v=New-Object System.Speech.Synthesis.SpeechSynthesizer;$v.SelectVoice('Microsoft Heera');$v.Rate=2;$v.SetOutputToWaveFile($f);$v.Speak($lines[$i]);$v.Dispose();$timings += [math]::Round(((Get-Item $f).Length-44)/(24000*2)+0.8,2)}
$app=New-Object -ComObject PowerPoint.Application;$app.Visible=-1;$deck=$null
try{$deck=$app.Presentations.Open($source,$false,$false,$false);for($i=1;$i -le $deck.Slides.Count;$i++){$s=$deck.Slides.Item($i);$f=Join-Path $audioDir ('slide-{0:00}.wav' -f $i);$a=$s.Shapes.AddMediaObject2($f,$false,$true,0,0,1,1);$a.AnimationSettings.PlaySettings.PlayOnEntry=$true;$a.AnimationSettings.PlaySettings.HideWhileNotPlaying=$true;$s.SlideShowTransition.AdvanceOnTime=$true;$s.SlideShowTransition.AdvanceTime=$timings[$i-1]};if(Test-Path $pptx){Remove-Item $pptx -Force};if(Test-Path $out){Remove-Item $out -Force};$deck.SaveAs($pptx);$deck.CreateVideo($out,$true,5,1920,30,85);Start-Sleep 20;$d=(Get-Date).AddMinutes(15);$last=-1;$stable=0;while((Get-Date)-lt $d){$len=if(Test-Path $out){(Get-Item $out).Length}else{0};if($len -gt 1MB -and $len -eq $last){$stable++}else{$stable=0};if($stable -ge 3){break};$last=$len;Start-Sleep 10};Get-Item $out|Select-Object FullName,Length}finally{if($deck){try{$deck.Close()}catch{}};$app.Quit()}
