export const GET = async () => {
  const headers = {
    'Content-Type': 'text/plain; charset=utf-8'
  };

  const body = [
    '# Robots.txt generated by Astro',
    '# Valid directives only; non-standard entries removed',
    '',
    'User-agent: *',
    'Allow: /',
    'Disallow: /admin/',
    'Disallow: /api/',
    '',
    '# Explicit opt-outs for known AI crawlers (standard User-agent blocks)',
    'User-agent: GPTBot',
    'Disallow: /',
    'User-agent: ChatGPT-User',
    'Disallow: /',
    'User-agent: Bytespider',
    'Disallow: /',
    'User-agent: Claude-Web',
    'Disallow: /',
    'User-agent: Google-Extended',
    'Disallow: /',
    '',
    'Sitemap: https://dolphinhouse-alibaug.com/sitemap.xml'
  ].join('\n') + '\n';

  return new Response(body, { headers });
};