export const GET = async () => {
  const headers = {
    'Content-Type': 'text/plain; charset=utf-8'
  };

  const body = [
    '# Robots.txt generated by Astro',
    '# Valid directives only; non-standard entries removed',
    '',
    'User-agent: *',
    'Allow: /',
    'Disallow: /admin/',
    'Disallow: /api/',
    '',
    '# AI crawlers allowed for GEO (Generative Engine Optimization)',
    '# Allowing Google-Extended, GPTBot, and ChatGPT-User so AI engines can cite this site',
    'User-agent: GPTBot',
    'Allow: /',
    'Disallow: /admin/',
    'Disallow: /api/',
    'User-agent: ChatGPT-User',
    'Allow: /',
    'Disallow: /admin/',
    'Disallow: /api/',
    'User-agent: Google-Extended',
    'Allow: /',
    'User-agent: Claude-Web',
    'Allow: /',
    'Disallow: /admin/',
    'Disallow: /api/',
    '',
    '# Block known spam bots',
    'User-agent: Bytespider',
    'Disallow: /',
    '',
    'Sitemap: https://dolphinhouse-alibaug.com/sitemap.xml'
  ].join('\n') + '\n';

  return new Response(body, { headers });
};